name: Chrome-Bookmarks-CICD

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Testing env var
      run: echo $TEST
    - name: Prepare the zip file for the extension
      run: zip -r extension.zip .
    - name: Get Access Token for the Google Web Store
      run: |
        REFRESH_TOKEN_RESPONSE=$(curl "https://accounts.google.com/o/oauth2/token" --silent -d "refresh_token=$REFRESH_TOKEN&client_id=$CLIENT_ID&client_secret=$CLIENT_SECRET&grant_type=refresh_token")
        ACCESS_TOKEN=$(echo $REFRESH_TOKEN_RESPONSE | jq --raw-output .access_token)
    - name: Upload to the Google Web Store
      run: |
        curl -H "Authorization: Bearer $ACCESS_TOKEN" -H "x-goog-api-version: 2" -X PUT -T "./extension.zip" --silent https://www.googleapis.com/upload/chromewebstore/v1.1/items/$APP_ID
