name: Browser Bookmarks - CICD

on:
  push:
    tags:
      - '*.*.*'

jobs:
  cicd:
    runs-on: ubuntu-18.04
    env:
      APP_ID: ${{ secrets.APP_ID }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
    steps:
      - uses: actions/checkout@v1
      - name: Ensure that the branch is tagged, and matches the manifest version
        run: |
          MANIFEST_VERSION=$(cat manifest.json | jq --raw-output .version)
          TAG_VERSION=$(git tag --points-at HEAD)

          if [ "$MANIFEST_VERSION" != "$TAG_VERSION" ]; then
            echo "**************************************************************************"
            echo "* Manifest and Git tag versions do not match, skipping the publishing... *"
            echo "**************************************************************************"
            exit 1
          fi
      - name: Prepare the zip file for the extension
        run: |
          zip -rq extension.zip .
      - name: Get Access Token for the Google Web Store
        run: |
          REFRESH_TOKEN_RESPONSE=$(curl "https://accounts.google.com/o/oauth2/token" --silent -d "refresh_token=$REFRESH_TOKEN&client_id=$CLIENT_ID&client_secret=$CLIENT_SECRET&grant_type=refresh_token")
          echo -e "ACCESS_TOKEN=$(echo $REFRESH_TOKEN_RESPONSE | jq --raw-output .access_token)\n" >> .vars
      - name: Upload to the Google Web Store
        run: |
          source .vars
          curl -H "Authorization: Bearer $ACCESS_TOKEN" -H "x-goog-api-version: 2" -X PUT -T "./extension.zip" --silent https://www.googleapis.com/upload/chromewebstore/v1.1/items/$APP_ID
      - name: Publish the Item
        run: |
          source .vars
          curl -H "Authorization: Bearer $ACCESS_TOKEN" -H "x-goog-api-version: 2" -H "Content-Length: 0" -X POST --silent https://www.googleapis.com/chromewebstore/v1.1/items/$APP_ID/publish
