name: Chrome-Bookmarks-CICD

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      APP_ID: ${{ secrets.APP_ID }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
    steps:
      - uses: actions/checkout@v1
      - name: Get new package version
        run: |
          echo -e "NEW_VERSION=$(cat manifest.json | jq --raw-output .version)\n" >> .vars
      - name: Get published package version from the current tag (if exists)
        run: |
          echo "Placeholder for now..."
      - name: Prepare the zip file for the extension
        run: |
          zip -rq extension.zip .
      - name: Get Access Token for the Google Web Store
        run: |
          REFRESH_TOKEN_RESPONSE=$(curl "https://accounts.google.com/o/oauth2/token" --silent -d "refresh_token=$REFRESH_TOKEN&client_id=$CLIENT_ID&client_secret=$CLIENT_SECRET&grant_type=refresh_token")
          echo -e "ACCESS_TOKEN=$(echo $REFRESH_TOKEN_RESPONSE | jq --raw-output .access_token)\n" >> .vars
      - name: Upload to the Google Web Store
        run: |
          source .vars
          curl -H "Authorization: Bearer $ACCESS_TOKEN" -H "x-goog-api-version: 2" -X PUT -T "./extension.zip" --silent https://www.googleapis.com/upload/chromewebstore/v1.1/items/$APP_ID
      - name: Publish the Item
        run: |
          source .vars
          curl -H "Authorization: Bearer $ACCESS_TOKEN" -H "x-goog-api-version: 2" -H "Content-Length: 0" -X POST --silent https://www.googleapis.com/chromewebstore/v1.1/items/$APP_ID/publish
